#!/bin/bash

source "$(dirname $0)/helper.sh"

# cd to dir of the current tab so options will be sub-files
cd "$CUR_DIR"
pwd

TYPE=$(cat << EOF | fzf
tgz
zip
tar.bz2
tar
EOF)

if [[ $TYPE == "tgz" ]]; then
    tar -zcf "${HOVERED_FILE}.tgz" "$HOVERED_FILE"
elif [[ $TYPE == "zip" ]]; then
    zip -r "${HOVERED_FILE}.zip" "$HOVERED_FILE"
elif [[ $TYPE == "tar.bz2" ]]; then
    tar -jcf "${HOVERED_FILE}.tar.bz2" "$HOVERED_FILE"
else
    exit 1
fi

echo "refresh" >> "$CMD_FILE"
