#!/usr/bin/env sh

IFS="$(printf '\n\r')"

if ! type fzf >/dev/null 2>&1; then
    printf "fzf missing"
    read -r _
    exit 1
fi

sel=$(cat $HOME/.paths | fzf --preview 'fzfpreview {1}' -d '\t' --with-nth 2,3,4,5,6 --bind 'enter:become(echo {1})')

if [ -n "$sel" ]; then
    if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
        exit 0
    fi

    echo "cd $sel" >> "$2"
fi
