#!/usr/bin/env bash

IFS="$(printf '\n\r')"

if ! type fzf >/dev/null 2>&1; then
    printf "fzf missing"
    read -r _
    exit 1
fi

export FZF_PREVIEW_DIR_CMD="ls -1"
if command -v eza; then
    export FZF_PREVIEW_DIR_CMD="eza --icons=always --color=always -1"
fi

sel=$(cat $HOME/.paths | fzf -d '\t' --preview '$FZF_PREVIEW_DIR_CMD {1}' --with-nth 2,3,4,5,6 --bind 'enter:execute(echo {1})+abort')

if [ -n "$sel" ]; then
    if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
        exit 0
    fi

    echo "cd $sel" >> "$2"
fi
