#!/bin/bash -x

source "$(dirname $0)/helper.sh"

onedir() {
    DIR=""
    local SINGLE_DIR=1
    local DIRS=0
    #-r  raw input - disables interpretion of backslash escapes and line-continuation in the read data
    while IFS= read -r line; do
        # echo "$line"
        if [[ "$line" == "." ]]; then
            :
        elif [[ "$line" == ".." ]]; then
            :
        elif [[ -d "$EXTDIR/$line" ]]; then
            # echo "Adding to DIRS for $line"
            ((DIRS++))
            DIR="$line"
        else
            # echo "$line is not a dir"
            SINGLE_DIR=0
        fi
    done < <(ls -a1 -- "$EXTDIR")

    if [[ $SINGLE_DIR == 1 && $DIRS == 1 ]]; then
        return 0
    fi
    return 1
}

to_sub() {
    if onedir; then
        mv "$EXTDIR/$DIR" "$CUR_DIR/"
    else
        mkdir "$STEM"
        (
            shopt -s dotglob
            mv "$EXTDIR"/* "$STEM/"
        )
    fi
}

# Ask BFM to refresh no matter what
echo "refresh" >> "$CMD_FILE"

cd $CUR_DIR

# Extract everything to a TMP dir and see if there is a containing folder
EXTDIR=$(mktemp -d) || die "Error creating temp directory for extraction"
trap 'rm -rf -- "$EXTDIR"' EXIT

TARGZ_RE='\.tar\.gz$'
TGZ_RE='\.tgz$'
TARBZ_RE='\.tar\.bz2$'
TAR_RE='\.(tar)$'
ZIP_RE='\.zip$'
GZ_RE='\.gz$'

if [[ "$HOVERED_FILE" =~ $TARGZ_RE ]]; then
    # Works in Bash 3.2 (macOS), unlike ${HOVERED_FILE::-4}
    STEM=${HOVERED_FILE%???????}
    gum spin --title "Untarring $HOVERED_FILE" -- tar -zxf "$HOVERED_FILE" -C "$EXTDIR"
    to_sub

elif [[ "$HOVERED_FILE" =~ $TGZ_RE ]]; then
    STEM=${HOVERED_FILE%????}
    gum spin --title "Untarring $HOVERED_FILE" -- tar -zxf "$HOVERED_FILE" -C "$EXTDIR"
    to_sub

elif [[ "$HOVERED_FILE" =~ $TARBZ_RE ]]; then
    STEM=${HOVERED_FILE%????????}
    gum spin --title "Untarring $HOVERED_FILE" -- tar -jxf "$HOVERED_FILE" -C "$EXTDIR"
    to_sub

elif [[ "$HOVERED_FILE" =~ $TAR_RE ]]; then
    STEM=${HOVERED_FILE%????}
    gum spin --title "Untarring $HOVERED_FILE" -- tar -xf "$HOVERED_FILE" -C "$EXTDIR"
    to_sub

elif [[ "$HOVERED_FILE" =~ $ZIP_RE ]]; then
    STEM=${HOVERED_FILE%????}
    gum spin --title "Unzipping $HOVERED_FILE" -- unzip -d "$EXTDIR" "$HOVERED_FILE"
    to_sub

elif [[ "$HOVERED_FILE" =~ $GZ_RE ]]; then
    gum spin --title "GUnzipping $HOVERED_FILE" -- gunzip "$HOVERED_FILE"

else
    echo "Did not recognize file extension"
    exit 1
fi
