Set FontFamily "Hack Nerd Font Mono"
Set Padding 20
Set Width 1000
Set Height 800
Set Framerate 16

Output tmux.gif

# Let cursor initialize
Sleep 0.1s

Set TypingSpeed 50ms

Type "tmux new-session -n BFM bfm"
Sleep 1.5s
Enter

Sleep 1s
Set TypingSpeed 100ms
Type "/bet"
Sleep 0.5s
Enter
Sleep 0.5s
Type "l"
Sleep 0.5s

Type "/main"
Sleep 0.5s
Enter
Sleep 0.5s
Type "e"
Sleep 4s

Type ":wq"
Enter

Sleep 2s
